# == Camera Parameters == #

# Image dimensions
width: 960
height: 540

# Intrinsic
focal_x: 698.9716186523438
focal_y: 698.9716186523438
skew: -0.555483153496783
cx: 532.1896362304688
cy: 320.1039733886719
k1: -0.152506391410118
k2: -0.0317086378242961
k3: 0.0504283387678160
p1: -0.00284011515561270
p2: 0.000437253973299189

# Extrinsic
r_vec:
  - [0, -1,  0]
  - [0,  0, -1]
  - [1,  0,  0]

t_vec:
  - -0.018 #0.203
  - -0.203 #-0.018
  - 0.05 #-0.050

# Cone classifier parameters
bb_height_coef: 1.4                   # Coefficient bounding box height estimation (orig. value: 1.71740618)
bb_width_factor: 0.8 #0.73                 # Percentage of bounding box hight that should be used as bb width
classifier_img_size: 32               # Input image size that is used for the classifier
engine_path: "/engines/model_multibatch.engine"  # Bath of classifier engine file
classes: ["no_cone", "yellow_cone", "blue_cone", "orange_cone", "large_orange_cone"]
colors:
  - [128,   0, 128]                   # purple
  - [255, 255,   0]                   # yellow
  - [  0,   0, 255]                   # blue
  - [255, 165,   0]                   # orange
  - [255,   0,   0]                   # red