# == Camera Parameters == #

# Image dimensions
width: 640
height: 320

# Intrinsic
focal_x: 701.369863014
focal_y: 701.369863014
skew: 0.0 #-0.555483153496783
cx: 320
cy: 180
k1: 0
k2: 0
k3: 0
p1: 0
p2: 0

# Extrinsic
r_vec:
  - [0, -1,  0]
  - [0,  0, -1]
  - [1,  0,  0]

t_vec:
  - 0.003843059946351502
  - 0.6947744101849331
  - 1.8888207001689468

# Cone classifier parameters
bb_height_coef: 1.0                   # Coefficient bounding box height estimation (orig. value: 1.71740618)
bb_width_factor: 0.8 #0.73                 # Percentage of bounding box hight that should be used as bb width
classifier_img_size: 32               # Input image size that is used for the classifier
engine_path: "/engines/model_multibatch.engine"  # Bath of classifier engine file
classes: ["no_cone", "yellow_cone", "blue_cone", "orange_cone", "large_orange_cone"]
colors:
  - [128,   0, 128]                   # purple
  - [255, 255,   0]                   # yellow
  - [  0,   0, 255]                   # blue
  - [255, 165,   0]                   # orange
  - [255,   0,   0]                   # red